---------------
Reynaldo Lima
Lista 9 - Questão 1
---------------------------

In [123]:
import numpy as np

def Jacobi_cinco_iteracoes(A, b, n, x):
    #Parâmetros de entrada:
    #n: dimensão da matriz (poderia usar len(A))
    #A e b: matrizes do sistema linear
    #v: chute inicial
    for k in range(0, 5):
        v = x
        for i in range(0, n):
            s = 0
            for j in range(0, n):
                if j != i:
                    s = s + A[i, j]*v[j]
            x[i] = (b[i]-s)*(1/A[i,i])
    print(x, '\n')

def Jacobi_erro(A, b, n, x, erro):
    #Parâmetros de entrada:
    #n: dimensão da matriz (poderia usar len(A))
    #A e b: matrizes do sistema linear
    #v: chute inicial
    k = 0
    while np.linalg.norm(b - A@x, 2) > erro:
        v = x
        k = k+1
        for i in range(0, n):
            s = 0
            for j in range(0, n):
                if j != i:
                    s = s + A[i, j]*v[j]
            x[i] = (b[i]-s)/A[i,i]
    print(x, '\n\n',k, 'iterações\n')
    
def Gauss_Seidel_iteracoes(A, b, n, x):
    #Parâmetros de entrada:
    #n: dimensão da matriz (poderia usar len(A))
    #A e b: matrizes do sistema linear
    #v: chute inicial
    v = np.zeros((3, 1))
    for k in range(0, 5):
        v = x
        for i in range(0, n):
            s = 0
            for j in range(0, i):
                s = s + A[i, j]*x[j]
            for j in range(i+1, n):
                s = s + A[i, j]*v[j]
            x[i] = (b[i]-s)*(1/A[i,i])
    print(x, '\n')
    
    
def GS_erro(A, b, n, x, erro):
    #Parâmetros de entrada:
    #n: dimensão da matriz (poderia usar len(A))
    #A e b: matrizes do sistema linear
    #v: chute inicial
    k = 0
    while np.linalg.norm(b - A@x, 2) > erro:
        v = x
        k = k+1
        for i in range(0, n):
            s = 0
            for j in range(0, i):
                s = s + A[i, j]*x[j]
            for j in range(i+1, n):
                s = s + A[i, j]*v[j]
            x[i] = (b[i]-s)*(1/A[i,i])
    print(x, '\n\n',k, 'iterações\n')

Questão 1:

In [132]:
A = np.matrix([[5., 1, 1], [1., 4, 1], [1., 1, 3]])
b = np.matrix([[10.], [12.], [12.]])
x0 = np.matrix([[0.], [0.], [0.]])
print('---------------------------------\nJacobi com 5 iterações\n')
Jacobi_cinco_iteracoes(A, b, 3, x0)
x0 = np.matrix([[0.], [0.], [0.]])
print('---------------------------------\nJacobi com erro de 1e-5\n')
Jacobi_erro(A, b, 3, x0, 10**(-5))
x0 = np.matrix([[0.], [0.], [0.]])
print('---------------------------------\nGauss-Seidel com 5 iterações\n')
Gauss_Seidel_iteracoes(A, b, 3, x0)
x0 = np.matrix([[0.], [0.], [0.]])
print('---------------------------------\nGauss-Seidel com erro de 1e-5\n')
GS_erro(A, b, 3, x0, 10**(-5))

---------------------------------
Jacobi com 5 iterações

[[0.99971759]
 [1.99986516]
 [3.00013908]] 

---------------------------------
Jacobi com erro de 1e-5

[[1.00000085]
 [1.99999983]
 [2.99999978]] 

 8 iterações

---------------------------------
Gauss-Seidel com 5 iterações

[[0.99971759]
 [1.99986516]
 [3.00013908]] 

---------------------------------
Gauss-Seidel com erro de 1e-5

[[1.00000085]
 [1.99999983]
 [2.99999978]] 

 8 iterações

